name: 'AI Code Reviewer'
description: 'Reviews pull request changes using a local ollama instance and posts feedback as a comment'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  url:
    description: 'Ollama URL'
    required: true
    default: 'http://127.0.0.1:11434/api/generate'
  model:
    description: 'The LLM model to review the code with'
    required: true
    default: 'qwen2.5-coder:14b-instruct-q8_0'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'purple'
